package com.berry.cmd.po;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   音乐
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table music
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 24 18:41:50 CST 2018
 */
public class Music implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.keyid
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    private Integer keyid;

    /**
     * Database Column Remarks:
     *   名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.name
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   作者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.author
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    private String author;

    /**
     * Database Column Remarks:
     *   发行时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.pub_date
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    private Date pubDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table music
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.keyid
     *
     * @return the value of music.keyid
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public Integer getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.keyid
     *
     * @param keyid the value for music.keyid
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public void setKeyid(Integer keyid) {
        this.keyid = keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.name
     *
     * @return the value of music.name
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.name
     *
     * @param name the value for music.name
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.author
     *
     * @return the value of music.author
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.author
     *
     * @param author the value for music.author
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.pub_date
     *
     * @return the value of music.pub_date
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public Date getPubDate() {
        return pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.pub_date
     *
     * @param pubDate the value for music.pub_date
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    public void setPubDate(Date pubDate) {
        this.pubDate = pubDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Music other = (Music) that;
        return (this.getKeyid() == null ? other.getKeyid() == null : this.getKeyid().equals(other.getKeyid()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getAuthor() == null ? other.getAuthor() == null : this.getAuthor().equals(other.getAuthor()))
            && (this.getPubDate() == null ? other.getPubDate() == null : this.getPubDate().equals(other.getPubDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKeyid() == null) ? 0 : getKeyid().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getAuthor() == null) ? 0 : getAuthor().hashCode());
        result = prime * result + ((getPubDate() == null) ? 0 : getPubDate().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", keyid=").append(keyid);
        sb.append(", name=").append(name);
        sb.append(", author=").append(author);
        sb.append(", pubDate=").append(pubDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}