package com.berry.cmd.po;

import java.util.Date;

/**
 * Database Table Remarks:
 *   世界
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table world
 *
 * @mbg.generated do_not_delete_during_merge Tue Apr 24 15:28:11 CST 2018
 */
public class World {
    /**
     * Database Column Remarks:
     *   关键字
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column world.keyid
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    private Integer keyid;

    /**
     * Database Column Remarks:
     *   姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column world.name
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    private String name;

    /**
     * Database Column Remarks:
     *   生日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column world.birthday
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    private Date birthday;

    /**
     * Database Column Remarks:
     *   宽度
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column world.width
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    private Integer width;

    /**
     * Database Column Remarks:
     *   是否可达
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column world.can_arrive
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    private Integer can_arrive;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column world.keyid
     *
     * @return the value of world.keyid
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public Integer getKeyid() {
        return keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column world.keyid
     *
     * @param keyid the value for world.keyid
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public void setKeyid(Integer keyid) {
        this.keyid = keyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column world.name
     *
     * @return the value of world.name
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column world.name
     *
     * @param name the value for world.name
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column world.birthday
     *
     * @return the value of world.birthday
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column world.birthday
     *
     * @param birthday the value for world.birthday
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column world.width
     *
     * @return the value of world.width
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column world.width
     *
     * @param width the value for world.width
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column world.can_arrive
     *
     * @return the value of world.can_arrive
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public Integer getCan_arrive() {
        return can_arrive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column world.can_arrive
     *
     * @param can_arrive the value for world.can_arrive
     *
     * @mbg.generated Tue Apr 24 15:28:11 CST 2018
     */
    public void setCan_arrive(Integer can_arrive) {
        this.can_arrive = can_arrive;
    }
}