package com.berry.cmd.dao;

import com.berry.cmd.po.World;

public interface WorldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    int deleteByPrimaryKey(Integer keyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    int insert(World record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    int insertSelective(World record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    World selectByPrimaryKey(Integer keyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    int updateByPrimaryKeySelective(World record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table world
     *
     * @mbg.generated Tue Apr 24 18:41:50 CST 2018
     */
    int updateByPrimaryKey(World record);
}